#!/bin/bash
# ============================================================
# start.sh — Launch an autonomous bio-AFE design agent
#
# Usage:
#   bash start.sh <block>
#
# Examples:
#   bash start.sh bandgap
#   bash start.sh inamp
#   bash start.sh adc
#   bash start.sh pga
#   bash start.sh filter
#   bash start.sh integration
#
# The agent runs in tmux and persists after SSH disconnect.
#   To watch:   tmux attach -t <block>
#   To detach:  Ctrl+B, D
#   To stop:    tmux kill-session -t <block>
# ============================================================

BLOCK="${1:?Usage: bash start.sh <block_name>}"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
BLOCK_DIR="$PROJECT_DIR/blocks/$BLOCK"

echo ""
echo "================================================"
echo "  Bio-AFE Agent: $BLOCK"
echo "  Block dir:     $BLOCK_DIR"
echo "  $(date)"
echo "================================================"
echo ""

# Verify block exists
if [ ! -f "$BLOCK_DIR/program.md" ] || [ ! -f "$BLOCK_DIR/specs.json" ]; then
    echo "ERROR: $BLOCK_DIR/program.md or specs.json not found."
    echo "Available blocks:"
    ls "$PROJECT_DIR/blocks/"
    exit 1
fi

# Verify tools
echo "Checking tools..."
for tool in ngspice python3 claude git; do
    if command -v $tool &>/dev/null; then
        echo "  $tool: OK ($(which $tool))"
    else
        echo "  $tool: MISSING!"
        exit 1
    fi
done
echo ""

# Kill existing session if any
tmux kill-session -t "$BLOCK" 2>/dev/null || true

# Build the prompt — reference top-level CLAUDE.md + block-specific files
PROMPT="You are an autonomous analog circuit designer. You will work indefinitely until manually stopped.

SETUP:
1. Read ../../CLAUDE.md — it contains the full experiment loop, self-evaluation rules, and Phase A/B structure.
2. Read program.md — block-specific evaluation criteria and testbenches.
3. Read specs.json — your pass/fail targets. DO NOT edit this file.
4. Read CLAUDE.md — block-specific design freedom, anti-benchmaxxing rules, and sanity checks.
5. Read ../../interfaces.md — signal contracts with other blocks and biosignal characteristics.
6. Read ../../master_spec.json — system-level context.

THEN: Begin the autonomous experiment loop as described in ../../CLAUDE.md.
- Phase A: Meet all specs (score = 1.0).
- Phase B: PVT corners, Monte Carlo, waveform analysis, all plots from program.md.
- After EVERY run: study the plots critically. Do the waveforms look physically correct? See ../../CLAUDE.md for the full self-evaluation checklist.
- NEVER STOP. Loop forever. Do not ask for permission. The human is away.
- Search the web for papers, SKY130 examples, textbook techniques.
- README.md is your progress dashboard — update after every keeper with plots and analysis.
- Commit and push after every keeper."

# Start in detached tmux
tmux new-session -d -s "$BLOCK" \
    "cd '$BLOCK_DIR' && claude --dangerously-skip-permissions -p '$PROMPT'"

sleep 1
echo "================================================"
echo "  AGENT STARTED: $BLOCK"
echo "================================================"
echo ""
tmux ls
echo ""
echo "  To watch:   tmux attach -t $BLOCK"
echo "  To detach:  Ctrl+B, D"
echo "  To stop:    tmux kill-session -t $BLOCK"
echo "  Progress:   cat $BLOCK_DIR/README.md"
echo "  Status:     python $PROJECT_DIR/orchestrate.py"
echo ""
