#!/bin/bash
# ============================================================
# start.sh - Launch an autonomous bio-AFE design agent
#
# Usage:
#   bash start.sh <block>
#
# Examples:
#   bash start.sh bandgap
#   bash start.sh inamp
#   bash start.sh adc
#   bash start.sh pga
#   bash start.sh filter
#   bash start.sh integration
#
# The agent runs in tmux and persists after SSH disconnect.
#   To watch:   tmux attach -t <block>
#   To detach:  Ctrl+B, D
#   To stop:    tmux kill-session -t <block>
# ============================================================

BLOCK="${1:?Usage: bash start.sh <block_name>}"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
BLOCK_DIR="$PROJECT_DIR/blocks/$BLOCK"

echo ""
echo "================================================"
echo "  Bio-AFE Agent: $BLOCK"
echo "  Block dir:     $BLOCK_DIR"
echo "  $(date)"
echo "================================================"
echo ""

# Verify block exists
if [ ! -f "$BLOCK_DIR/program.md" ] || [ ! -f "$BLOCK_DIR/specs.json" ]; then
    echo "ERROR: $BLOCK_DIR/program.md or specs.json not found."
    echo "Available blocks:"
    ls "$PROJECT_DIR/blocks/"
    exit 1
fi

# Verify tools
echo "Checking tools..."
for tool in ngspice python3 claude git; do
    if command -v $tool &>/dev/null; then
        echo "  $tool: OK ($(which $tool))"
    else
        echo "  $tool: MISSING!"
        exit 1
    fi
done
echo ""

# Kill existing session if any
tmux kill-session -t "$BLOCK" 2>/dev/null || true

# Build the prompt - reference root program.md plus block-specific files
PROMPT="You are an autonomous analog circuit designer. You will work indefinitely until manually stopped.

SETUP:
1. Read ../../program.md - the global mission, experiment loop, evaluation doctrine, and git discipline.
2. Read ../../CLAUDE.md - short wrapper that points back to the canonical root instructions.
3. Read program.md - everything about this block: purpose, specs, testbenches, evaluation rules, design freedom.
4. Read specs.json - your pass/fail targets. DO NOT edit this file.
5. Read ../../interfaces.md - signal contracts with other blocks and biosignal characteristics.
6. Read ../../master_spec.json - system-level context.
7. Use python ../../orchestrate.py to inspect block readiness when needed.
8. Begin the autonomous design loop immediately after reading.

THEN: Begin the autonomous experiment loop as described in ../../program.md.
- Phase A: Meet all specs honestly.
- Phase B: PVT corners, Monte Carlo where available, waveform analysis, and all plots required by program.md.
- After EVERY run: study the plots critically. If plots and device physics disagree with the scalar, trust the plots.
- Be tougher on the evaluation than the minimum required by program.md. Try to break weak designs.
- NEVER STOP. Loop forever. Do not ask for permission. The human is away.
- Search the web for papers, SKY130 examples, and textbook techniques.
- README.md is your progress dashboard - update after every keeper with plots and analysis.
- Commit and push after every keeper.
- Log every run in results.tsv and discard failed or weaker ideas cleanly."

# Start in detached tmux
tmux new-session -d -s "$BLOCK" \
    "cd '$BLOCK_DIR' && claude --dangerously-skip-permissions -p '$PROMPT'"

sleep 1
echo "================================================"
echo "  AGENT STARTED: $BLOCK"
echo "================================================"
echo ""
tmux ls
echo ""
echo "  To watch:   tmux attach -t $BLOCK"
echo "  To detach:  Ctrl+B, D"
echo "  To stop:    tmux kill-session -t $BLOCK"
echo "  Progress:   cat $BLOCK_DIR/README.md"
echo "  Status:     python $PROJECT_DIR/orchestrate.py"
echo ""
